# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BufKcat < Formula
  desc "Kafka consumer CLI tool with protobuf decoding using buf"
  homepage "https://github.com/HurSungYun/buf-kcat"
  version "0.0.8"
  license "MIT"

  depends_on "buf" => :optional
  depends_on "protobuf" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/HurSungYun/buf-kcat/releases/download/v0.0.8/buf-kcat_0.0.8_Darwin_x86_64.tar.gz"
      sha256 "a65dfd2f223ac72263db4adb6b102eca29bf878812d5977ffedbc121f9846921"

      def install
        bin.install "buf-kcat"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/HurSungYun/buf-kcat/releases/download/v0.0.8/buf-kcat_0.0.8_Darwin_arm64.tar.gz"
      sha256 "042ad2910550877dc4d7b3155fed5e2222ee462b86a9ff31abbb69fe569221ab"

      def install
        bin.install "buf-kcat"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/HurSungYun/buf-kcat/releases/download/v0.0.8/buf-kcat_0.0.8_Linux_x86_64.tar.gz"
      sha256 "c725d3240989daf0d972d479b602e7fe8439e4fd87a1590ca76c87ad8de54006"
      def install
        bin.install "buf-kcat"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/HurSungYun/buf-kcat/releases/download/v0.0.8/buf-kcat_0.0.8_Linux_arm64.tar.gz"
      sha256 "b81a4cf17b593bb8c58899a8320e2283f6939db4fadfa0648aee9377ee50a124"
      def install
        bin.install "buf-kcat"
      end
    end
  end

  test do
    system "#{bin}/buf-kcat", "--help"
  end
end
