# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BufKcat < Formula
  desc "Kafka consumer CLI tool with protobuf decoding using buf"
  homepage "https://github.com/HurSungYun/buf-kcat"
  version "0.1.0"
  license "MIT"

  depends_on "buf" => :optional
  depends_on "protobuf" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/HurSungYun/buf-kcat/releases/download/v0.1.0/buf-kcat_0.1.0_Darwin_x86_64.tar.gz"
      sha256 "72bd2741af1bd458bbe616eb054524a1609fedaac86cf490355b36e5dfc057e0"

      def install
        bin.install "buf-kcat"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/HurSungYun/buf-kcat/releases/download/v0.1.0/buf-kcat_0.1.0_Darwin_arm64.tar.gz"
      sha256 "ceee39f31d47bb1773cec64d60922ae0efa226e5e7e10b2f61165ad30ca3bb44"

      def install
        bin.install "buf-kcat"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/HurSungYun/buf-kcat/releases/download/v0.1.0/buf-kcat_0.1.0_Linux_x86_64.tar.gz"
      sha256 "9dfce3d9aa9d6b1eed9a1e95a6b17dbf8731bd408c769461fd2b3fe9d59c2657"
      def install
        bin.install "buf-kcat"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/HurSungYun/buf-kcat/releases/download/v0.1.0/buf-kcat_0.1.0_Linux_arm64.tar.gz"
      sha256 "53eaa9645b93e8026fa4b05b20dbd0f635ab48a39e7f7caf7dd22a5a97ba63af"
      def install
        bin.install "buf-kcat"
      end
    end
  end

  test do
    system "#{bin}/buf-kcat", "--help"
  end
end
