# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BufKcat < Formula
  desc "Kafka consumer CLI tool with protobuf decoding using buf"
  homepage "https://github.com/HurSungYun/buf-kcat"
  version "0.0.5"
  license "MIT"

  depends_on "buf" => :optional
  depends_on "protobuf" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/HurSungYun/buf-kcat/releases/download/v0.0.5/buf-kcat_0.0.5_Darwin_x86_64.tar.gz"
      sha256 "0115d19db03da1d0b3f901083f8a20accd61073bf04966898a3cd12d7c12a83c"

      def install
        bin.install "buf-kcat"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/HurSungYun/buf-kcat/releases/download/v0.0.5/buf-kcat_0.0.5_Darwin_arm64.tar.gz"
      sha256 "c197a84be90e9fe2e64be2965ce52f8055de727fa78a1c7cd8f25ee12ec9f1e2"

      def install
        bin.install "buf-kcat"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/HurSungYun/buf-kcat/releases/download/v0.0.5/buf-kcat_0.0.5_Linux_x86_64.tar.gz"
      sha256 "070debbe6cdf264552be205114ad3735fee90e81180fbd68eda2b78582220787"
      def install
        bin.install "buf-kcat"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/HurSungYun/buf-kcat/releases/download/v0.0.5/buf-kcat_0.0.5_Linux_arm64.tar.gz"
      sha256 "660f05c2151fe245248eef0c64c8873f7d6a23358e50247c9e5821f37c6721c9"
      def install
        bin.install "buf-kcat"
      end
    end
  end

  test do
    system "#{bin}/buf-kcat", "--help"
  end
end
